services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8000:5173"
    depends_on:
      - backend
