version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  web:
    build: ./frontend
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - backend
